import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Beta and calibration terms — Replay Method", description: "Terms for contributing a replay or requesting a Replay Method beta analysis.", alternates: { canonical: "/beta-terms" } };

export default function BetaTermsPage() {
  return <main className="legal-shell">
    <nav className="legal-nav"><Link className="brand" href="/"><span className="logo" aria-hidden="true" /><span>replay<span>method</span></span></Link><Link href="/analyze">← Back to analysis</Link></nav>
    <header><span>BETA ANALYSIS TERMS</span><h1>One real match. No fake promise.</h1><p>These terms explain private replay calibration, the free beta analysis, what you may submit and what Replay Method can—and cannot—promise.</p><small>Last updated: 21 August 2026</small></header>
    <div className="legal-grid"><aside><b>The deal today</b><p>Replay intake is free when open. No card is collected, and intake may remain closed during quality validation.</p><Link href="/privacy">Read our privacy notice →</Link></aside><article>
      <section><h2>1. Private calibration contributions</h2><p>When the dedicated Rocket League calibration intake is shown as open, you may contribute an original PC .replay so Replay Method can privately test, label and improve detector quality. A contribution is research input: it does not create or promise a player analysis, report, coaching result or response. You must give the separate calibration consent and identify the player whose evidence should be followed.</p></section>
      <section><h2>2. The beta analysis service</h2><p>You may request analysis from a supported match reference, original Rocket League .replay file, or gameplay video/VOD only when the relevant analysis intake is shown as open. A PC replay can support frame-exact telemetry; video is assessed only from what is visible and audible in the supplied footage. League and VALORANT automation requires approved, opt-in Riot access. Replay Method may reject unsupported or insufficient evidence. Capacity and turnaround are not guaranteed.</p></section>
      <section><h2>3. Automated analysis and quality review</h2><p>The target service parses supported match data, produces versioned findings and may use an AI language layer to explain them. It stops when evidence is insufficient. Calibration moments require independent qualified review before they can count toward a public detector gate, but routine player delivery is not promised to include a human coach.</p></section>
      <section><h2>4. Your submission</h2><p>You confirm that you may share the evidence and that it does not contain unlawful, malicious or unnecessarily sensitive material. You retain ownership and grant Replay Method limited permission to store, review and transform it for the calibration or beta-analysis purpose you explicitly selected.</p></section>
      <section><h2>5. Private report link</h2><p>Your report uses a high-entropy private link instead of a public profile. Anyone who obtains that link may be able to view the report, so keep it private and contact us if you believe it was exposed.</p></section>
      <section><h2>6. No rank guarantee</h2><p>The report is educational feedback, not a guarantee of rank, rating, win rate or competitive result. Outcomes depend on the evidence, game, other players and how you apply the plan.</p></section>
      <section><h2>7. Feedback and case studies</h2><p>You may rate a completed report. Replay Method will use your words publicly only when you separately authorize an anonymous quotation. We do not create or publish fake player reviews.</p></section>
      <section><h2>8. Publishers and contact</h2><p>Replay Method is independent and is not affiliated with, endorsed by or sponsored by Riot Games, Psyonix or Epic Games. Game names identify compatibility only. Commercial Rocket League functionality remains closed until platform and intellectual-property clearance is complete. Questions or deletion requests can be sent to <a href="mailto:contact@replaymethod.xyz?subject=Replay%20Method%20beta">contact@replaymethod.xyz</a>. Swedish law applies without limiting mandatory consumer rights.</p></section>
    </article></div>
  </main>;
}
