import type { Metadata } from "next";
import Link from "next/link";
import { CustomerFooter, CustomerHeader } from "../components/CustomerChrome";

export const metadata: Metadata = { title: "Beta and calibration terms — Replay Method", description: "Terms for contributing a replay or requesting a Replay Method beta analysis.", alternates: { canonical: "/beta-terms" } };

export default function BetaTermsPage() {
  return <main className="legal-shell">
    <CustomerHeader compact right={<Link className="rm-header-cta" href="/analyze">Analyze <span aria-hidden="true">↗</span></Link>} />
    <header><span>EARLY ACCESS BETA TERMS</span><h1>One real match. No fake promise.</h1><p>These terms explain private replay calibration, the free Early Access analysis, what you may submit and what Replay Method can—and cannot—promise.</p><small>Last updated: 23 August 2026</small></header>
    <div className="legal-grid"><aside><b>The deal today</b><p>Replay intake is free when open. No card is collected, and intake may remain closed during quality validation.</p><Link href="/privacy">Read our privacy notice →</Link></aside><article>
      <section><h2>1. Private calibration contributions</h2><p>When the dedicated Rocket League calibration intake is shown as open, you may contribute an original PC .replay so Replay Method can privately test, label and improve detector quality. A contribution is research input: it does not create or promise a player analysis, report, coaching result or response. You must give the separate calibration consent and identify the player whose evidence should be followed.</p></section>
      <section><h2>2. The beta analysis service</h2><p>You may request analysis from supported original Rocket League .replay files when the analysis intake is shown as open. PC replays support frame-exact telemetry. Console replay export is not supported by the automated beta. Replay Method may reject unsupported evidence. Capacity and turnaround are not guaranteed.</p></section>
      <section><h2>3. Automated analysis and quality review</h2><p>The Early Access service parses supported match data and returns verified match facts. It may also return a clearly marked experimental coaching interpretation when repeated timestamped evidence in that replay clears the current Early Access policy. Unsupported findings abstain locally. Experimental output is not a formally validated detector result, does not mean the individual report was human-reviewed, and is not a promise of professional validation. Independent expert validation continues separately.</p></section>
      <section><h2>4. Your submission</h2><p>You confirm that you may share the evidence and that it does not contain unlawful, malicious or unnecessarily sensitive material. You retain ownership and grant Replay Method limited permission to store and transform it for the beta report you requested. A customer analysis replay is not used for calibration, training or evaluation unless you give a separate explicit opt-in through the calibration contribution flow.</p></section>
      <section><h2>5. Private report link</h2><p>Your report uses a high-entropy private link instead of a public profile. Anyone who obtains that link may be able to view the report, so keep it private and contact us if you believe it was exposed.</p></section>
      <section><h2>6. No rank guarantee</h2><p>The report is educational feedback, not a guarantee of rank, rating, win rate or competitive result. Outcomes depend on the evidence, game, other players and how you apply the plan.</p></section>
      <section><h2>7. Feedback and case studies</h2><p>You may rate a completed report. This is product feedback, not expert Rocket League ground truth, and it does not validate a detector. Replay Method will use your words publicly only when you separately authorize an anonymous quotation. We do not create or publish fake player reviews.</p></section>
      <section><h2>8. Publishers and contact</h2><p>Replay Method is independent and is not affiliated with, endorsed by or sponsored by Psyonix, Epic Games or Rocket League. The game name identifies compatibility only. Commercial Rocket League functionality remains closed until platform and intellectual-property clearance is complete. Questions or deletion requests can be sent to <a href="mailto:contact@replaymethod.xyz?subject=Replay%20Method%20beta">contact@replaymethod.xyz</a>. Swedish law applies without limiting mandatory consumer rights.</p></section>
    </article></div><CustomerFooter />
  </main>;
}
