import type { Metadata } from "next";
import Link from "next/link";
import { CustomerFooter, CustomerHeader } from "../components/CustomerChrome";

export const metadata: Metadata = {
  title: "Privacy — Replay Method",
  description: "How Replay Method handles beta analyses, match evidence, waitlist and website data.",
  alternates: { canonical: "/privacy" }
};

export default function PrivacyPage() {
  return <main className="legal-shell">
    <CustomerHeader right={<Link className="rm-header-cta" href="/analyze">Analyze <span aria-hidden="true">↗</span></Link>} />
    <header><span>PRIVACY</span><h1>Your data should never be another hidden system.</h1><p>This notice explains what Replay Method collects when you contribute a replay, request an analysis, receive a beta report, join product updates or accept a private product-review invitation—and how you stay in control.</p><small>Last updated: 23 August 2026</small></header>
    <div className="legal-grid">
      <aside><b>Quick version</b><p>We use the match evidence you submit to create your private report. A customer analysis replay is not used for calibration, training or evaluation unless you give a separate explicit opt-in. Product-update email is optional. We do not sell your data or use advertising cookies.</p><a href="mailto:contact@replaymethod.xyz?subject=Replay%20Method%20privacy%20request">Make a privacy request →</a></aside>
      <article>
        <section><h2>1. Who is responsible?</h2><p>Replay Method is an early-stage project operated by Rafael Westin in Sweden. For access, correction, deletion or other privacy questions, email <a href="mailto:contact@replaymethod.xyz?subject=Replay%20Method%20privacy%20request">contact@replaymethod.xyz</a>.</p></section>
        <section><h2>2. What we collect</h2><p>For a private Rocket League calibration contribution we store your email, exact in-game player name, rank group, original replay file, file fingerprint, file size, referral data, consent record and review status. This research intake is separate from a player analysis and does not create or promise a report.</p><p>For a Rocket League analysis we store your email, platform, rank and goal, player context you choose to provide, the original replay files you upload, optional notes, the resulting report, workflow status and any feedback. Replay evidence can contain gaming usernames or chat from other players; submit only material you are permitted to share. We also record referral data and basic funnel events with a temporary anonymous session identifier. Optional product-update consent is stored separately.</p><p>For an invited private commercial or UX review we store the stable account identity supplied by ChatGPT sign-in, the assigned review lane, checklist scores and findings, issue steps, recommendations, session context and any screenshot or short recording you choose to attach. This product feedback is stored separately from Rocket League detector labels and is available only to the invited reviewer and the owner.</p><p>Private report ownership uses a one-time email verification token. After verification, an essential HttpOnly session cookie keeps your report history available on that device for up to 90 days. Only a one-way hash of each token is stored; these essential credentials are not used for advertising.</p></section>
        <section><h2>3. Why we use it</h2><ul><li>Secure and privately review Rocket League contributions submitted through the separate calibration form with explicit calibration consent.</li><li>Secure, parse and analyze the match evidence you requested us to process.</li><li>Create and deliver your private Replay Method report and current focus when you request analysis.</li><li>Compare later matches when you choose to return.</li><li>Collect structured Early Access product feedback separately from expert detector labels.</li><li>Collect reproducible commercial and UX feedback from specifically invited product reviewers.</li><li>Notify you about report status when transactional email is available.</li><li>Send product and beta-access updates only when you separately opt in.</li><li>Measure the beta funnel, prevent abuse and improve reliability without recording sensitive replay contents in analytics.</li></ul><p>Submitting a customer analysis authorizes processing needed to deliver that report. It does not authorize use of that replay for detector calibration, model training or evaluation. Those purposes require a separate, explicit opt-in through the calibration contribution flow. Public beta feedback is product evidence and is not treated as independent Rocket League ground truth. Invited product-review processing and security rely on our legitimate interest in testing and improving the product with the reviewer who accepted the assignment. Optional marketing email is based on separate consent. Security and limited anonymous measurement rely on our legitimate interest in operating and improving the beta.</p></section>
        <section><h2>4. Who receives it</h2><p>Data is available only to Replay Method, qualified reviewers authorized for private calibration, specifically invited product reviewers for their own assigned form, and providers necessary for authentication, hosting, private file storage, automated replay, video or match processing, AI-assisted language synthesis, security and transactional email. The AI language layer receives compact structured findings rather than an entire raw replay or video where practical. We do not sell or rent personal data and do not publish a replay, report, product-review attachment or quote without separate permission.</p></section>
        <section><h2>5. How long we keep it</h2><p>Beta submissions and reports are retained while needed to deliver the service, compare later reports and improve the method. We review inactive analysis data for deletion within 12 months. Raw uploaded replay and gameplay-video files may be deleted earlier when no longer needed. Private product-review drafts, submissions and attachments are reviewed for deletion within 12 months or earlier when the review has been incorporated and the evidence is no longer needed. Waitlist records remain until you withdraw consent or they are no longer needed for beta and launch. You may request deletion at any time.</p></section>
        <section><h2>6. Cookies, browser storage and advertising</h2><p>Replay Method uses an essential HttpOnly session cookie for verified report ownership. It expires after no more than 90 days and is not available to browser scripts. Our hosting and security provider may also set short-lived, strictly necessary cookies for bot detection and service protection. A temporary anonymous analytics identifier may live in session storage until you close the tab, and private report identifiers may be saved locally on the device that created them. We do not currently set advertising cookies or load advertising pixels. If that changes, this notice and any required consent control will be updated before the technology is enabled.</p></section>
        <section><h2>7. Your choices and rights</h2><p>You may withdraw consent at any time. You may also request access, correction, deletion, restriction or portability of your personal data, and object where processing relies on legitimate interest. After email verification, <Link href="/reports">My reports</Link> provides a machine-readable export and permanent account deletion. Deletion is held until an active paid period has ended so billing rights are not orphaned. You may always use the contact email instead. Withdrawing consent does not affect processing that was lawful before withdrawal.</p></section>
        <section><h2>8. International processing</h2><p>Infrastructure providers may process data outside the European Economic Area. Where required, transfers must use recognized safeguards such as an adequacy decision or approved contractual clauses.</p></section>
        <section><h2>9. Complaints and changes</h2><p>You may complain to the Swedish Authority for Privacy Protection, <a href="https://www.imy.se/" rel="noreferrer">IMY</a>. We may update this notice as the beta develops. Material changes affecting your choice will be communicated before they take effect.</p></section>
      </article>
    </div><CustomerFooter />
  </main>;
}
