import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Service and waitlist terms — Replay Method",
  description: "Terms for Replay Method beta access, subscriptions, cancellation and consumer rights.",
  alternates: { canonical: "/terms" }
};

export default function TermsPage() {
  return <main className="legal-shell">
    <nav className="legal-nav"><Link className="brand" href="/" aria-label="Replay Method home"><span className="logo">↻</span><span>replay<span>method</span></span></Link><Link href="/">← Back to Replay Method</Link></nav>
    <header><span>SERVICE AND WAITLIST TERMS</span><h1>No card. No hidden purchase.</h1><p>These terms explain today&apos;s free beta request and the paid subscription terms that will apply only after checkout is separately opened.</p><small>Last updated: 20 August 2026</small></header>
    <div className="legal-grid">
      <aside><b>The deal today</b><p>You are joining a waitlist, not buying a subscription. Nothing is charged and no payment details are collected.</p><Link href="/privacy">Read our privacy notice →</Link></aside>
      <article>
        <section><h2>1. Operator and current offer</h2><p>Replay Method is an early-stage service operated by Rafael Westin in Sweden. Contact: <a href="mailto:contact@replaymethod.xyz">contact@replaymethod.xyz</a>. Today you may join a free waitlist or preserve a supported beta request. Checkout is technically closed; no card is collected and no paid contract is formed. Complete trader, address and tax details will be displayed before any paid checkout is activated.</p></section>
        <section><h2>2. Waitlist and beta availability</h2><p>A valid signup gives you priority consideration for beta and launch access. It does not guarantee an invitation, launch date, supported game, turnaround time or feature. Replay intake may remain closed while quality validation is in progress. League and VALORANT automation additionally depends on approved official access.</p></section>
        <section><h2>3. Published subscription terms</h2><p>If paid access is later activated, the displayed plans are $12 monthly, $27 every three months, $49 every six months or $89 every twelve months. The selected total is charged at checkout and at each renewal for the same billing period until canceled. Each plan includes four successfully completed analyses in a rolling 30-day allowance; unused analyses do not roll over. The final order page will repeat the total, billing interval, tax treatment and included service before purchase. Joining the waitlist or using a free check never starts a subscription.</p></section>
        <section><h2>4. Age, cancellation and access</h2><p>Paid access is limited to purchasers aged 18 or over. When billing is active, customers may cancel through the secure customer portal or contact support. Cancellation stops the next renewal; paid access normally continues through the already-paid period and completed reports remain readable. A cancellation request does not remove statutory rights.</p></section>
        <section><h2>5. Withdrawal and refunds</h2><p>Consumers in the European Union generally have a 14-day right to withdraw from an online service contract. If you expressly ask for digital service performance to begin during that period, rules on proportionate payment for service already supplied may apply. Replay Method will not ask you to waive mandatory rights. Faulty, unavailable or misdescribed service is handled under applicable consumer law; contact support for correction, cancellation or a refund review. Any checkout will present the required withdrawal information before payment.</p></section>
        <section><h2>6. Beta product and acceptable use</h2><p>Replay Method is under development. You may submit only evidence you are permitted to share and must not upload unlawful, malicious or unnecessarily sensitive material. Capacity, inputs and reports may change. Automated findings are educational and may stop when evidence is insufficient; routine human coaching is not promised.</p></section>
        <section><h2>7. No competitive-result guarantee</h2><p>Replay Method is designed to identify patterns and focus practice. Results depend on the player, game, available data and application of feedback. We do not guarantee a rank, rating, win rate or improvement.</p></section>
        <section><h2>8. Game publishers and intellectual property</h2><p>Replay Method is independent and is not affiliated with, endorsed by or sponsored by Riot Games, Psyonix, Epic Games, Valve or their products. Game names are used only to identify compatibility. You retain rights in your submission and grant Replay Method only the limited permission described in the <Link href="/beta-terms">beta analysis terms</Link>. Paid Rocket League functionality will remain closed until commercial platform and intellectual-property use has been separately cleared.</p><p>Portions of materials, if any, may be trademarks or copyrighted works of Epic Games, Inc. All rights are reserved by Epic. This service is not official and is not endorsed by Epic.</p></section>
        <section><h2>9. Privacy, leaving and account deletion</h2><p>You may leave the waitlist through an unsubscribe link or by contacting support. Verified users can export or delete account data from <Link href="/reports">My reports</Link>, subject to completion of any active paid period. See the <Link href="/privacy">privacy notice</Link> for details.</p></section>
        <section><h2>10. Law, complaints and contact</h2><p>Swedish law applies, without limiting mandatory consumer protections in your country of residence. Questions, withdrawal notices, complaints or refund requests can be sent to <a href="mailto:contact@replaymethod.xyz?subject=Replay%20Method%20support">contact@replaymethod.xyz</a>. We will provide any additional legally required business and dispute-resolution information before paid checkout opens.</p></section>
      </article>
    </div>
  </main>;
}
